#!/bin/sh

ARGS=`getopt -a -o r:l:et -l host:,changedir: -- "$@"`  
[ $? -ne 0 ] && usage  
#set -- "${ARGS}"  
eval set -- "${ARGS}" 

set -x

[ -z $TFTP_HOST ]  && TFTP_HOST='192.168.8.232'

singleMod="no"
while true  
do  
    case "$1" in 
    -r)  
	    singleMod="yes"
            REMOTE_FILE="$2" 
            shift  
            ;;  
    -l) 
	    singleMod="yes"
            LOCAL_FILE="$2" 
            shift  
            ;;  
    -i|--host)  
            TFTP_HOST="$2" 
            shift  
            ;;  
    -C|--changedir)
            dest_dir="$2" 
            shift  
            ;;  
    -t)
	  tarFlag="yes"
	;;
    -e)
	chmodFlag="yes"
	;;
    --)  
            shift  
            break 
            ;;  
    esac  
shift  
done


if [singleMod == "yes"]; then
	echo "tftp -g $TFTP_HOST -r $REMOTE_FILE -l $LOCAL_FILE"
	[ tftp -g $TFTP_HOST -r $REMOTE_FILE -l $LOCAL_FILE ] || exit 1
	[ "tarFlag" = "yes" ] && tar -zcvf $LOCAL_FILE 
	[ "chmodFlag" = "yes" ] && chmod 777 $LOCAL_FILE
else
	
	filelist="$@"
	for file in  filelist; do
		echo "tftp -g $TFTP_HOST -r $file &"
		tftp -g $TFTP_HOST -r $file && [ "chmodFlag" = "yes" ] && chmod 777  $file  &
	done
fi
